server:
  port: 8080

spring:
  application:
    name: 'account'

  datasource:
    url: 'jdbc:postgresql://localhost:5432/intdb'
    driverClassName: org.postgresql.Driver
    username: root
    password: 'password'

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true